fragment EpisodeFields on Episode {
  id
  episode
  endEpisode
  title
  url
  resource
  type
  released
  watched
}

fragment MediaLinkFields on Media {
  mediaId
  mediaType
  slug
  title {
    ru
    be
    en
    alt
  }
  poster
  year
  status
  language
  hidden
}

fragment MediaFields on Media {
  mediaId
  mediaType
  slug
  title {
    ru
    be
    en
    alt
  }
  description {
    ru
    be
    en
  }
  studio
  status
  poster
  wallpaper
  country
  year
  view
  trailer
  download
  donation
  language
  genres
  franchise
  relations {
    ...MediaLinkFields
  }
  disableComments
  isBelarusianAuthor
  hidden
  dmca
  rating
  markStats {
    total
    watching
    watched
    dropped
    planned
  }
  mark {
    status
  }
  favorite
  episodes {
    ...EpisodeFields
  }
  chapters {
    id
    chapter
    title
  }
}

query RandomMediaQuery {
  randomMedia {
    ...MediaFields
  }
}
