package net.anibel.app

import android.app.Activity
import android.app.LocaleManager
import android.content.Context
import android.content.res.Configuration
import android.os.Build
import android.os.LocaleList
import androidx.annotation.StringRes
import java.util.Locale

internal enum class AppLanguage(val tag: String, val label: String) {
    Belarusian("be", "Беларуская"), English("en", "English")
}

internal object Language {
    private lateinit var application: Context
    private lateinit var localized: Context
    fun initialize(context: Context) {
        application = context.applicationContext
        if (Build.VERSION.SDK_INT >= 33) {
            val manager = application.getSystemService(LocaleManager::class.java)
            if (manager.applicationLocales.isEmpty) manager.applicationLocales = LocaleList.forLanguageTags("be")
        }
        wrap(application)
    }
    fun current(context: Context): AppLanguage {
        val tag = if (Build.VERSION.SDK_INT >= 33)
            context.getSystemService(LocaleManager::class.java).applicationLocales.toLanguageTags().substringBefore(',')
        else context.getSharedPreferences("preferences", Context.MODE_PRIVATE).getString("language", "be")
        return AppLanguage.entries.firstOrNull { it.tag == tag } ?: AppLanguage.Belarusian
    }
    fun wrap(context: Context): Context {
        val locale = Locale.forLanguageTag(current(context).tag)
        Locale.setDefault(locale)
        val configuration = Configuration().apply { setLocales(LocaleList(locale)) }
        val wrapped = context.createConfigurationContext(configuration)
        if (::application.isInitialized) localized = application.createConfigurationContext(configuration)
        return wrapped
    }
    fun select(activity: Activity, language: AppLanguage) {
        if (current(activity) == language) return
        if (Build.VERSION.SDK_INT >= 33) activity.getSystemService(LocaleManager::class.java).applicationLocales = LocaleList.forLanguageTags(language.tag)
        else {
            activity.getSharedPreferences("preferences", Context.MODE_PRIVATE).edit().putString("language", language.tag).apply()
            activity.recreate()
        }
    }
    fun text(@StringRes id: Int, vararg args: Any): String = localized.getString(id, *args)
}

internal fun ui(@StringRes id: Int, vararg args: Any): String = Language.text(id, *args)

/** Translate known API keys; names supplied by contributors stay unchanged. */
internal fun keyLabel(key: String): String = when (key.lowercase(Locale.ROOT)) {
    "all" -> ui(R.string.choice_all)
    "active" -> ui(R.string.choice_active)
    "ready" -> ui(R.string.choice_ready)
    "anime" -> ui(R.string.catalog_anime)
    "manga" -> ui(R.string.catalog_manga)
    "cinema" -> ui(R.string.catalog_cinema)
    "games" -> ui(R.string.catalog_games)
    "books" -> ui(R.string.catalog_books)
    "sub" -> ui(R.string.choice_sub)
    "dub" -> ui(R.string.choice_dub)
    "other" -> ui(R.string.choice_other)
    "ongoing" -> ui(R.string.choice_ongoing)
    "finished" -> ui(R.string.choice_finished)
    "china" -> ui(R.string.choice_china)
    "notselected" -> ui(R.string.choice_unselected)
    "watching" -> ui(R.string.choice_watching)
    "watched" -> ui(R.string.choice_watched)
    "reading" -> ui(R.string.choice_reading)
    "read" -> ui(R.string.choice_read)
    "playing" -> ui(R.string.choice_playing)
    "played" -> ui(R.string.choice_played)
    "planned" -> ui(R.string.planned)
    "dropped" -> ui(R.string.dropped)
    "queued" -> ui(R.string.choice_queued)
    "downloading" -> ui(R.string.choice_downloading)
    "completed" -> ui(R.string.choice_completed)
    "failed" -> ui(R.string.choice_failed)
    "cancelled" -> ui(R.string.choice_cancelled)
    "about" -> ui(R.string.about)
    "content" -> ui(R.string.content_tab)
    "comments" -> ui(R.string.comments_tab)
    "related" -> ui(R.string.related_tab)
    "all_sources" -> ui(R.string.all_sources)
    "dementia" -> ui(R.string.metadata_dementia)
    "martial-arts" -> ui(R.string.metadata_martial_arts)
    "shoujo-ai" -> ui(R.string.metadata_shoujo_ai)
    "shounen-ai" -> ui(R.string.metadata_shounen_ai)
    "slice-of-life" -> ui(R.string.metadata_slice_of_life)
    "super-power" -> ui(R.string.metadata_super_power)
    "yaoi" -> ui(R.string.metadata_yaoi)
    "yuri" -> ui(R.string.metadata_yuri)
    "detective" -> ui(R.string.metadata_detective)
    "job" -> ui(R.string.metadata_job)
    "erotica" -> ui(R.string.metadata_erotica)
    "action" -> ui(R.string.metadata_action)
    "боевые искусства" -> ui(R.string.metadata_martial_arts)
    "martial arts" -> ui(R.string.metadata_martial_arts)
    "приключения" -> ui(R.string.metadata_adventure)
    "adventure" -> ui(R.string.metadata_adventure)
    "фэнтези" -> ui(R.string.metadata_fantasy)
    "fantasy" -> ui(R.string.metadata_fantasy)
    "фантастика" -> ui(R.string.metadata_sci_fi)
    "sci-fi" -> ui(R.string.metadata_sci_fi)
    "sci fi" -> ui(R.string.metadata_sci_fi_variant)
    "научная фантастика" -> ui(R.string.metadata_sci_fi_variant)
    "драма" -> ui(R.string.metadata_drama)
    "drama" -> ui(R.string.metadata_drama)
    "комедия" -> ui(R.string.metadata_comedy)
    "comedy" -> ui(R.string.metadata_comedy)
    "романтика" -> ui(R.string.metadata_romance)
    "romance" -> ui(R.string.metadata_romance)
    "ужасы" -> ui(R.string.metadata_horror)
    "horror" -> ui(R.string.metadata_horror)
    "детектив" -> ui(R.string.metadata_detective)
    "mystery" -> ui(R.string.metadata_mystery)
    "мистика" -> ui(R.string.metadata_mystery)
    "триллер" -> ui(R.string.metadata_thriller)
    "thriller" -> ui(R.string.metadata_thriller)
    "спорт" -> ui(R.string.metadata_sports)
    "sports" -> ui(R.string.metadata_sports)
    "музыка" -> ui(R.string.metadata_music)
    "школа" -> ui(R.string.metadata_school)
    "school" -> ui(R.string.metadata_school)
    "повседневность" -> ui(R.string.metadata_slice_of_life_variant)
    "slice of life" -> ui(R.string.metadata_slice_of_life_variant)
    "psychological" -> ui(R.string.metadata_psychological)
    "historical" -> ui(R.string.metadata_historical)
    "military" -> ui(R.string.metadata_military)
    "меха" -> ui(R.string.metadata_mecha)
    "mecha" -> ui(R.string.metadata_mecha)
    "магия" -> ui(R.string.metadata_magic)
    "magic" -> ui(R.string.metadata_magic)
    "сэйнэн" -> ui(R.string.metadata_seinen)
    "сейнен" -> ui(R.string.metadata_seinen)
    "seinen" -> ui(R.string.metadata_seinen)
    "сёнэн" -> ui(R.string.metadata_shonen)
    "сёнен" -> ui(R.string.metadata_shonen)
    "shounen" -> ui(R.string.metadata_shonen)
    "shonen" -> ui(R.string.metadata_shonen)
    "сёдзё" -> ui(R.string.metadata_shojo)
    "сёдзе" -> ui(R.string.metadata_shojo)
    "shoujo" -> ui(R.string.metadata_shoujo)
    "shojo" -> ui(R.string.metadata_shojo)
    "дзёсэй" -> ui(R.string.metadata_josei)
    "josei" -> ui(R.string.metadata_josei)
    "ecchi" -> ui(R.string.metadata_ecchi)
    "хентай" -> ui(R.string.metadata_hentai)
    "hentai" -> ui(R.string.metadata_hentai)
    "исекай" -> ui(R.string.metadata_isekai)
    "isekai" -> ui(R.string.metadata_isekai)
    "гарем" -> ui(R.string.metadata_harem)
    "harem" -> ui(R.string.metadata_harem)
    "постапокалипсис" -> ui(R.string.metadata_post_apocalyptic)
    "post-apocalyptic" -> ui(R.string.metadata_post_apocalyptic)
    "киберпанк" -> ui(R.string.metadata_cyberpunk)
    "cyberpunk" -> ui(R.string.metadata_cyberpunk)
    "космос" -> ui(R.string.metadata_space)
    "space" -> ui(R.string.metadata_space)
    "сверхъестественное" -> ui(R.string.metadata_supernatural)
    "supernatural" -> ui(R.string.metadata_supernatural)
    "вампиры" -> ui(R.string.metadata_vampire)
    "vampire" -> ui(R.string.metadata_vampire)
    "вампир" -> ui(R.string.metadata_vampire)
    "демоны" -> ui(R.string.metadata_demons)
    "demons" -> ui(R.string.metadata_demons)
    "демон" -> ui(R.string.metadata_demons)
    "самураи" -> ui(R.string.metadata_samurai)
    "samurai" -> ui(R.string.metadata_samurai)
    "полиция" -> ui(R.string.metadata_police)
    "police" -> ui(R.string.metadata_police)
    "пародия" -> ui(R.string.metadata_parody)
    "parody" -> ui(R.string.metadata_parody)
    "kids" -> ui(R.string.metadata_kids)
    "gourmet" -> ui(R.string.metadata_gourmet)
    "медицина" -> ui(R.string.metadata_medical)
    "medical" -> ui(R.string.metadata_medical)
    "автомобили" -> ui(R.string.metadata_cars)
    "cars" -> ui(R.string.metadata_cars)
    "игры" -> ui(R.string.metadata_game)
    "game" -> ui(R.string.metadata_game)
    "безумие" -> ui(R.string.metadata_dementia)
    "супер сила" -> ui(R.string.metadata_super_power_variant)
    "super power" -> ui(R.string.metadata_super_power_variant)
    "сёнен-ай" -> ui(R.string.metadata_shounen_ai)
    "сёнэн-ай" -> ui(R.string.metadata_shounen_ai)
    "яой" -> ui(R.string.metadata_yaoi)
    "юри" -> ui(R.string.metadata_yuri)
    "cartoon" -> ui(R.string.metadata_cartoon)
    "serial" -> ui(R.string.metadata_serial)
    "film" -> ui(R.string.metadata_movie)
    "manhwa" -> ui(R.string.metadata_manhva)
    "manhva" -> ui(R.string.metadata_manhva)
    "manhua" -> ui(R.string.metadata_manhua)
    "oad" -> ui(R.string.metadata_oad)
    "classic" -> ui(R.string.metadata_classic)
    "novel" -> ui(R.string.metadata_novel)
    "tv" -> ui(R.string.metadata_tv)
    "movie" -> ui(R.string.metadata_movie)
    "ova" -> ui(R.string.metadata_ova)
    "ona" -> ui(R.string.metadata_ona)
    "special" -> ui(R.string.metadata_special)
    "tv_special" -> ui(R.string.metadata_tv_special)
    "web" -> ui(R.string.metadata_web)
    "picture" -> ui(R.string.metadata_picture)
    "cm" -> ui(R.string.metadata_cm)
    "pv" -> ui(R.string.metadata_pv)
    "short" -> ui(R.string.metadata_movie_short)
    "movie_short" -> ui(R.string.metadata_movie_short)
    "япония" -> ui(R.string.metadata_jp)
    "japan" -> ui(R.string.metadata_jp)
    "jp" -> ui(R.string.metadata_jp)
    "китай" -> ui(R.string.metadata_cn)
    "cn" -> ui(R.string.metadata_cn)
    "южная корея" -> ui(R.string.metadata_south_korea)
    "корея" -> ui(R.string.metadata_kr)
    "south korea" -> ui(R.string.metadata_south_korea)
    "korea" -> ui(R.string.metadata_kr)
    "kr" -> ui(R.string.metadata_kr)
    "сша" -> ui(R.string.metadata_united_states)
    "usa" -> ui(R.string.metadata_united_states)
    "us" -> ui(R.string.metadata_united_states)
    "united states" -> ui(R.string.metadata_united_states)
    "беларусь" -> ui(R.string.metadata_by)
    "belarus" -> ui(R.string.metadata_by)
    "by" -> ui(R.string.metadata_by)
    "россия" -> ui(R.string.metadata_ru)
    "russia" -> ui(R.string.metadata_ru)
    "ru" -> ui(R.string.metadata_ru)
    "украина" -> ui(R.string.metadata_ua)
    "ukraine" -> ui(R.string.metadata_ua)
    "ua" -> ui(R.string.metadata_ua)
    "польша" -> ui(R.string.metadata_poland)
    "poland" -> ui(R.string.metadata_poland)
    "франция" -> ui(R.string.metadata_france)
    "france" -> ui(R.string.metadata_france)
    "великобритания" -> ui(R.string.metadata_uk)
    "united kingdom" -> ui(R.string.metadata_uk)
    "uk" -> ui(R.string.metadata_uk)
    "германия" -> ui(R.string.metadata_germany)
    "germany" -> ui(R.string.metadata_germany)
    "италия" -> ui(R.string.metadata_italy)
    "italy" -> ui(R.string.metadata_italy)
    "канада" -> ui(R.string.metadata_canada)
    "canada" -> ui(R.string.metadata_canada)
    "тайвань" -> ui(R.string.metadata_taiwan)
    "taiwan" -> ui(R.string.metadata_taiwan)
    "гонконг" -> ui(R.string.metadata_hong_kong)
    "hong kong" -> ui(R.string.metadata_hong_kong)
    "таиланд" -> ui(R.string.metadata_thailand)
    "thailand" -> ui(R.string.metadata_thailand)
    "испания" -> ui(R.string.metadata_spain)
    "spain" -> ui(R.string.metadata_spain)
    else -> key
}
